# Site settings
title: DataOps.io
email: adam.bowen@delphix.com
description: >
  DataOps.io is an independent site built to extend the ideas of DataOps into 
  all applicable areas and disciplines of data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.dataops.io # the base hostname & protocol for your site
git_address: https://github.com/delphix/dataops.io
git_edit_address: https://github.com/delphix/dataops.io/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: delphix

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: US/Eastern
defaults:
- scope:
    path: _applications
    type: pages
  values:
    layout: default
    sectionid: application
    seo:
      type: "WebPage"

collections:
  applications:
    output: true
